# Generated by Django 3.1.5 on 2021-07-14 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="project title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "github_link",
                    models.URLField(unique=True, verbose_name="source code link"),
                ),
                (
                    "demo_link",
                    models.URLField(unique=True, verbose_name="link to demo"),
                ),
                (
                    "picture",
                    models.ImageField(upload_to="projects", verbose_name="screenshot"),
                ),
                (
                    "grid_size",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="grid size on desktop page",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(unique=True, verbose_name="order"),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
