# Generated by Django 3.1.5 on 2021-07-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210715_1757"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.about",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="core.contacts",
            ),
        ),
    ]
