# Generated by Django 3.1.5 on 2021-07-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210715_1831"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="github_link",
            new_name="source_link",
        ),
    ]
