# Generated by Django 3.1.5 on 2021-07-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210716_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='document',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='order'),
        ),
    ]
