# Generated by Django 3.1.5 on 2021-07-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210716_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='document',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='order'),
        ),
    ]
